carlossless/sinowealth-kb-tool

README.md
src/part.rs

https://github.com/carlossless/sinowealth-kb-tool/issues/7

Device: NuPhy Air96

---

README.md
src/part.rs

https://github.com/carlossless/sinowealth-kb-tool/issues/13

device: terport-tr95

---

README.md
src/part.rs

https://github.com/carlossless/sinowealth-kb-tool/issues/21

device: redragon-k6170-fizz

---

README.md
src/part.rs

https://github.com/carlossless/sinowealth-kb-tool/issues/25

device: royalkludge-rk100

---

README.md
src/part.rs

Added [Genesis Thor 300](https://genesis-zone.com/product/thor-300-outemu-blue).
Thanks to @gashtaan for testing on this keyboard!

device: genesis-thor-300

---

README.md
src/part.rs

Added [Genesis Thor 300 RGB](https://genesis-zone.com/product/thor-300-rgb-brown).
Thanks to @gashtaan for testing on this keyboard!

device: genesis-thor-300-rgb

---

README.md
src/main.rs
src/part.rs
tools/functional-test.sh

Customizable `usage` and `usage_page` selectors, addressing the need found in https://github.com/carlossless/sinowealth-kb-tool/issues/29#issuecomment-1868324411

usage_page and usage arguments

---

README.md
src/part.rs

https://github.com/carlossless/sinowealth-kb-tool/issues/29

device: weikav-sugar65

---

README.md
src/part.rs

https://github.com/carlossless/sinowealth-kb-tool/issues/37

device: royalkludge-rk61

---

README.md
src/part.rs

https://github.com/carlossless/sinowealth-kb-tool/issues/16

device: digitalalliance-meca-warrior-x

---

README.md
src/part.rs

https://github.com/carlossless/sinowealth-kb-tool/issues/40

device: xinmeng-xm-rf68

---

README.md
src/part.rs

https://github.com/carlossless/sinowealth-kb-tool/issues/28

device: royalkludge-rk71

---

README.md
src/part.rs

https://github.com/carlossless/sinowealth-kb-tool/issues/50

device: redragon-k641-shaco-pro

---

src/isp.rs

First encountered here: https://github.com/carlossless/sinowealth-kb-tool/issues/53#issue-2200835634

support for bootloaders with pid 0x1021

---

README.md
src/part.rs

https://github.com/carlossless/sinowealth-kb-tool/issues/53

device: glorious-model-o

---

README.md
src/part.rs

https://github.com/carlossless/sinowealth-kb-tool/issues/58

device: machenike-k500-b61

---

README.md
src/part.rs

https://github.com/carlossless/sinowealth-kb-tool/issues/60

device: redragon-k530-draconic-pro

---

README.md
src/part.rs

https://github.com/carlossless/sinowealth-kb-tool/issues/66

device: eyooso-z11

---

README.md
src/part.rs

https://github.com/carlossless/sinowealth-kb-tool/issues/61

device: redragon-k658-pro-se

---

README.md
src/part.rs

https://github.com/carlossless/sinowealth-kb-tool/issues/70

device: royalkludge-rkg68

---

README.md
src/part.rs

https://github.com/carlossless/sinowealth-kb-tool/issues/65

device: xinmeng-m71 (and yunzii-al71)

---

README.md
src/part.rs

add support for kzzi-k68pro
tested read on my keyboard is ok, not testing for write.
see image below for logs

	modified:   add kzzi k68 pro keyboard support

---

src/isp.rs

Addresses: https://github.com/carlossless/sinowealth-kb-tool/issues/83#issuecomment-2229042784

sorting all hid devices by their paths

---

README.md
src/part.rs

https://github.com/carlossless/sinowealth-kb-tool/issues/88

device: portronics-hydra10

---

README.md
src/part.rs

https://github.com/carlossless/sinowealth-kb-tool/issues/98

device: yinren-r108

---

README.md
src/part.rs

https://github.com/carlossless/sinowealth-kb-tool/issues/96

device: aula-f75

---

README.md
src/part.rs

https://github.com/carlossless/sinowealth-kb-tool/issues/101

device: magegee-mkstar61

---

.github/ISSUE_TEMPLATE/device-report.md

update device report template

---

README.md
src/device_spec.rs

https://github.com/carlossless/sinowealth-kb-tool/issues/111

device: eyooso-z82
